
include: package:flutter_lints/flutter.yaml

linter:
  rules:    
    public_member_api_docs: true
    always_use_package_imports: true
    avoid_redundant_argument_values: true
    prefer_single_quotes: true
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: false
    avoid_annotating_with_dynamic: false
    avoid_catches_without_on_clauses: false
    avoid_classes_with_only_static_members: false
    avoid_final_parameters: false
    avoid_positional_boolean_parameters: false
    avoid_types_on_closure_parameters: false
    cascade_invocations: false
    diagnostic_describe_all_properties: false
    omit_local_variable_types: false
    prefer_constructors_over_static_methods: false
    prefer_expression_function_bodies: false
    prefer_final_parameters: false
    prefer_int_literals: false
    require_trailing_commas: false
    sort_constructors_first: false
    unnecessary_final: false