name: moises
description: Moises.AI API Client for dart to access developer account data
version: 2.0.0

repository: https://github.com/whosramoss/moises
issue_tracker: https://github.com/whosramoss/moises/issues

screenshots:
  - description: Dart client to access Moises developer account data
    path: resources/images/icon.png


environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0 
  json_annotation: ^4.9.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1


flutter:
  uses-material-design: true