name: Build

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Check code and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      
      - name: Show Flutter version
        run: flutter --version
      
      - name: Restore packages
        run: flutter pub get

      - name: Run Analyze
        run: flutter analyze
      
      - name: Run tests
        run: flutter test --coverage --coverage-path ./coverage/lcov.info

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage/lcov.info

  coverage-codecov:
    needs: build
    name: Upload tests to codecov
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          verbose: true